

secrets: {}
persistentVolumes: {}
scratchPaths: {}
emptyDirs: {}
initContainers: {}


deploymentStrategy:
  enabled: false
  type: RollingUpdate
  rollingUpdate: {}

canary:
  enabled: false
  replicaCount: 1
  containerImage:
    repository: oebinu-db
    tag: v9
    pullPolicy: IfNotPresent

serviceMonitor:
  enabled: false

serviceAccount:
  name: ""
  create: false
  annotations: {}
  labels: {}

horizontalPodAutoscaler:
  enabled: false
  minReplicas: 1
  maxReplicas: 10



applicationName: "fxc-fxapi-test-v4"
imagePullSecrets: 
  - jfrog-pull-secret

containerImage:
  repository: artifactory.cibcdevops.com/virtual-docker-fxcenter/cloud/fxc-app-fxapi
  tag: v10
  pullPolicy: IfNotPresent

replicaCount: 1

containerPorts: 
  http:
    port: 8331
    protocol: TCP
  https:
    port: 8443
    protocol: TCP
  management:
    port: 9990
    protocol: TCP

containerCommand: null


podSecurityContext:
  fsGroup: 1000770000
  runAsUser: 1000770000
  # runAsGroup: 1000770000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault


securityContext: 
  privileged: false
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL


containerResources:
  requests:
    memory: "512Mi"
    cpu: "100m"
  # limits:
  #   memory: "1024Mi"
  #   cpu: "200m"  

    


###############################################
# CONFIGMAP
###############################################

configMaps:
  ## properties (2)
  # p01-properties-fxc:  
  # cm-fxc-properties:  
  #   as: volume
  #   mountPath: /opt/eap/standalone/configuration/fxc
  p02-properties-fxapi:
  # cm-fxapi-properties:
    as: volume
    mountPath: /opt/eap/standalone/configuration/fxapi/application.properties
    subPath: application-dit.properties


  ## jboss config (2)
  j02-jboss-standalone-xml:
  # cm-jboss-standalone:
    as: volume
    mountPath: /opt/eap/standalone/configuration/standalone.xml
    subPath: standalone_EAP7.4.11.xml

  j01-jboss-standalone-conf:
  # cm-jboss-standalone-conf:
    as: volume
    mountPath: /opt/eap/bin/standalone.conf
    subPath: standalone.conf

  #### application-config
  a01-application-config-ccr:
    as: volume    
    mountPath: /opt/eap/standalone/configuration/application-config-ccr.xml
    subPath: application-config-ccr.xml
  a02-application-config-ccs:
    as: volume   
    mountPath: /opt/eap/standalone/configuration/application-config-ccs.xml
    subPath: application-config-ccs.xml
  a03-application-config-fxc:
    as: volume   
    mountPath: /opt/eap/standalone/configuration/application-config-fxc.xml
    subPath: application-config-fxc.xml
  a04-application-config-stub:
    as: volume   
    mountPath: /opt/eap/standalone/configuration/application-config-stub.xml
    subPath: application-config-stub.xml

  ### shared instances xml (12)
  c01-ccr-stacks:
    as: volume   
    mountPath: /opt/eap/standalone/configuration/ccr-stacks.xml
    subPath: ccr-stacks.xml

  #### shared-instances
  s01-shared-instances-ecp:
    as: volume   
    mountPath: /opt/eap/standalone/configuration/shared-instances-ecp.xml
    subPath: shared-instances-ecp.xml
  s02-shared-instances-epm:
    as: volume   
    mountPath: /opt/eap/standalone/configuration/shared-instances-epm.xml
    subPath: shared-instances-epm.xml
  s03-shared-instances-eportal:
    as: volume   
    mountPath: /opt/eap/standalone/configuration/shared-instances-eportal.xml
    subPath: shared-instances-eportal.xml
  s04-shared-instances-fxc:
    as: volume   
    mountPath: /opt/eap/standalone/configuration/shared-instances-fxc.xml
    subPath: shared-instances-fxc.xml
  s05-shared-instances-pmo:
    as: volume   
    mountPath: /opt/eap/standalone/configuration/shared-instances-pmo.xml
    subPath: shared-instances-pmo.xml
  s06-shared-instances-simplii-ecp:
    as: volume   
    mountPath: /opt/eap/standalone/configuration/shared-instances-simplii-ecp.xml
    subPath: shared-instances-simplii-ecp.xml
  s07-shared-instances-simplii:
    as: volume   
    mountPath: /opt/eap/standalone/configuration/shared-instances-simplii.xml
    subPath: shared-instances-simplii.xml

###############################################
# SERVICE
###############################################

service:
  enabled: true
  ports:
    http:
      port: 80
      targetPort: 8331
      protocol: TCP
    https:
      port: 443
      targetPort: 8443
      protocol: TCP
    management:
      port: 9990
      targetPort: 9990
      protocol: TCP

###############################################
# INGRESS
###############################################

ingress:
  enabled: true
  ingressClassName: openshift-default
  hosts:
    - fxapi.v4.cibc.com
  path: "/"
  pathType: Prefix
  servicePort: 80
  additionalPaths:
  - path: "/https"
    pathType: Prefix
    servicePort: 443
  - path: "/mgmt"
    pathType: Prefix
    servicePort: 9990


lifecycleHooks:
  enabled: true


customResources:
  enabled: false
  resources:


